apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: bolt-proxy
  name: bolt-proxy-controller
spec:
  type: NodePort
  selector:
    app: bolt-proxy
  ports:
    - name: bolt
      port: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bolt-proxy
  name: bolt-proxy
spec:
  selector:
    matchLabels:
        app: bolt-proxy
  template:
    metadata:
      labels:
        app: bolt-proxy
    spec:
      containers:
        - name: bolt-proxy
          image:  bolt-proxy:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: "BOLT_PROXY_BIND"
              value: "0.0.0.0:8080"
            - name: "BOLT_PROXY_URI"
              value: "bolt://memgraph-service:7687"
            - name: "BOLT_PROXY_DEBUG"
              value: "1"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
              hostPort: 8080
