apiVersion: v1
kind: Service
metadata:
  name: memgraph-service
  labels:
    app: memgraph
spec:
  ports:
    - name: bolt
      port: 7687
  selector:
   app: memgraph
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memgraph
  labels:
    app: memgraph
spec:
  selector:
    matchLabels:
      app: memgraph
  template:
    metadata:
      labels:
        app: memgraph
    spec:
      containers:
        - name: memgraph
          image: memgraph/memgraph:1.5.0-community
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 7687
